apiVersion: v1
kind: Service
metadata:
  name: app-payment-service
  labels:
    app: app-payment
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: app-payment-lb
spec:
  type: LoadBalancer
  ports:
    - name: api
      port: 3333
      targetPort: 3333
    - name: prisma-studio
      port: 5555
      targetPort: 5555
  selector:
    app: app-payment
