apiVersion: v1
kind: Secret
metadata:
  name: app-payment-secret
  labels:
    app: app-payment
type: Opaque
stringData:
  POSTGRES_USER: "danilo"
  POSTGRES_PASSWORD: "danilo"
  MERCADO_PAGO_TOKEN: "TEST-2986934127013785-042221-fd19beb63eb9225c3ae626d6800cb09a-166893008"
