apiVersion: v1
kind: Secret
metadata:
  name: app-payment-secret
  labels:
    app: app-payment
type: Opaque
stringData:
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  MERCADO_PAGO_TOKEN: ${MERCADO_PAGO_TOKEN}
