apiVersion: v1
kind: Service
metadata:
  name: app-order-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: app-order-lb
spec:
  type: LoadBalancer
  selector:
    app: app-order
  ports:
    - name: http
      port: 8083
      targetPort: 8083