apiVersion: v1
kind: Service
metadata:
  name: app-client-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: app-client-lb
  labels:
    app: app-client-service
spec:
  type: LoadBalancer
  selector:
    app: app-client
  ports:
    - name: http
      port: 80
      targetPort: 8080
