apiVersion: v1
kind: Secret
metadata:
  name: app-client-secrets
  labels:
    app: app-client
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: mongodb://app-client-database-mongo-service:27017/app-client-database-mongo
