apiVersion: v1
kind: Service
metadata:
  name: app-product-service
  labels:
    app: app-product-service
spec:
  type: LoadBalancer
  selector:
    app: app-product
  ports:
    - name: http
      port: 80
      targetPort: 8081
