apiVersion: v1
kind: Secret
metadata:
  name: app-product-secrets
  labels:
    app: app-product
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: mongodb://admin:password123@mongodb:27018/product_db?authSource=admin
  MONGODB_USERNAME: admin
  MONGODB_PASSWORD: password123